"""Add index_constituents table for historical index membership tracking

Revision ID: 33796dd55aff
Revises: aa005fe89cd2
Create Date: 2025-11-29 09:50:45.279623

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33796dd55aff'
down_revision = 'aa005fe89cd2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fundamental_date', table_name='surveillance_fundamental_flags')
    op.create_index('idx_fundamental_date', 'surveillance_fundamental_flags', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_surveillance_date', table_name='surveillance_list')
    op.create_index('idx_surveillance_date', 'surveillance_list', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_price_movement_date', table_name='surveillance_price_movement')
    op.create_index('idx_price_movement_date', 'surveillance_price_movement', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_price_variation_date', table_name='surveillance_price_variation')
    op.create_index('idx_price_variation_date', 'surveillance_price_variation', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_variation_date', table_name='surveillance_price_variation', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_price_variation_date', 'surveillance_price_variation', [sa.text('date DESC')], unique=False)
    op.drop_index('idx_price_movement_date', table_name='surveillance_price_movement', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_price_movement_date', 'surveillance_price_movement', [sa.text('date DESC')], unique=False)
    op.drop_index('idx_surveillance_date', table_name='surveillance_list', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_surveillance_date', 'surveillance_list', [sa.text('date DESC')], unique=False)
    op.drop_index('idx_fundamental_date', table_name='surveillance_fundamental_flags', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_fundamental_date', 'surveillance_fundamental_flags', [sa.text('date DESC')], unique=False)
    # ### end Alembic commands ###
