"""Add Phase 2 calculated metrics columns

Revision ID: 8ba3cfea4bbe
Revises: e9dd4cc896bc
Create Date: 2025-12-25 06:00:38.569951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba3cfea4bbe'
down_revision = 'e9dd4cc896bc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calculated_metrics', sa.Column('change_1d_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='1-day % change'))
    op.add_column('calculated_metrics', sa.Column('change_1d_value', sa.Numeric(precision=12, scale=2), nullable=True, comment='1-day absolute change'))
    op.add_column('calculated_metrics', sa.Column('change_1w_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='1-week (5 trading days) % change'))
    op.add_column('calculated_metrics', sa.Column('change_1m_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='1-month (21 days) % change'))
    op.add_column('calculated_metrics', sa.Column('change_3m_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='3-month (63 days) % change'))
    op.add_column('calculated_metrics', sa.Column('change_6m_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='6-month (126 days) % change'))
    op.add_column('calculated_metrics', sa.Column('rs_percentile', sa.Numeric(precision=5, scale=2), nullable=True, comment='RS percentile rank (0-100) based on 1M change'))
    op.add_column('calculated_metrics', sa.Column('vars_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='Volatility-Adjusted RS = RS / ADR%'))
    op.add_column('calculated_metrics', sa.Column('varw_score', sa.Numeric(precision=10, scale=4), nullable=True, comment='Volatility-Adjusted Relative Weakness for laggards'))
    op.add_column('calculated_metrics', sa.Column('atr_14', sa.Numeric(precision=10, scale=4), nullable=True, comment='14-day ATR (Average True Range)'))
    op.add_column('calculated_metrics', sa.Column('atr_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='ATR as % of close (ATR/close * 100)'))
    op.add_column('calculated_metrics', sa.Column('adr_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='20-day Average Daily Range %'))
    op.add_column('calculated_metrics', sa.Column('today_range_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment="Today's (high-low)/close %"))
    op.add_column('calculated_metrics', sa.Column('volume_50d_avg', sa.BigInteger(), nullable=True, comment='50-day average volume'))
    op.add_column('calculated_metrics', sa.Column('rvol', sa.Numeric(precision=10, scale=4), nullable=True, comment='Relative Volume (today/50d avg)'))
    op.add_column('calculated_metrics', sa.Column('is_volume_surge', sa.Integer(), nullable=True, comment='1 if RVOL >= 1.5, else 0'))
    op.add_column('calculated_metrics', sa.Column('ema_10', sa.Numeric(precision=10, scale=4), nullable=True, comment='10-day EMA'))
    op.add_column('calculated_metrics', sa.Column('sma_20', sa.Numeric(precision=10, scale=4), nullable=True, comment='20-day SMA'))
    op.add_column('calculated_metrics', sa.Column('sma_50', sa.Numeric(precision=10, scale=4), nullable=True, comment='50-day SMA'))
    op.add_column('calculated_metrics', sa.Column('sma_100', sa.Numeric(precision=10, scale=4), nullable=True, comment='100-day SMA'))
    op.add_column('calculated_metrics', sa.Column('sma_200', sa.Numeric(precision=10, scale=4), nullable=True, comment='200-day SMA'))
    op.add_column('calculated_metrics', sa.Column('distance_from_ema10_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='(close - EMA10) / EMA10 * 100'))
    op.add_column('calculated_metrics', sa.Column('distance_from_sma50_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='(close - SMA50) / SMA50 * 100'))
    op.add_column('calculated_metrics', sa.Column('distance_from_sma200_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='(close - SMA200) / SMA200 * 100'))
    op.add_column('calculated_metrics', sa.Column('is_ma_stacked', sa.Integer(), nullable=True, comment='1 if close > EMA10 > SMA20 > SMA50 > SMA100 > SMA200'))
    op.add_column('calculated_metrics', sa.Column('atr_extension_from_sma50', sa.Numeric(precision=10, scale=4), nullable=True, comment='((close/SMA50) - 1) / (ATR/close) - how extended from SMA50 in ATR units'))
    op.add_column('calculated_metrics', sa.Column('lod_atr_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='((low - close) / ATR * 100) - Low of Day distance in ATR%'))
    op.add_column('calculated_metrics', sa.Column('is_lod_tight', sa.Integer(), nullable=True, comment='1 if LoD < 60% ATR, else 0'))
    op.add_column('calculated_metrics', sa.Column('darvas_20d_high', sa.Numeric(precision=15, scale=2), nullable=True, comment='20-day highest high'))
    op.add_column('calculated_metrics', sa.Column('darvas_20d_low', sa.Numeric(precision=15, scale=2), nullable=True, comment='20-day lowest low'))
    op.add_column('calculated_metrics', sa.Column('darvas_position_percent', sa.Numeric(precision=10, scale=4), nullable=True, comment='(close - low) / (high - low) * 100 within 20-day range'))
    op.add_column('calculated_metrics', sa.Column('is_new_20d_high', sa.Integer(), nullable=True, comment='1 if high >= 20-day max high'))
    op.add_column('calculated_metrics', sa.Column('is_new_20d_low', sa.Integer(), nullable=True, comment='1 if low <= 20-day min low'))
    op.add_column('calculated_metrics', sa.Column('orh_proxy', sa.Numeric(precision=15, scale=2), nullable=True, comment='Opening Range High proxy (first bar high)'))
    op.add_column('calculated_metrics', sa.Column('is_m30_reclaim', sa.Integer(), nullable=True, comment='1 if close > ORH proxy (approximation)'))
    op.add_column('calculated_metrics', sa.Column('stage_detail', sa.String(length=10), nullable=True, comment="Stage detail like '2A', '2B', '2C'"))
    op.add_column('calculated_metrics', sa.Column('universe_up_count', sa.Integer(), nullable=True, comment='# stocks up for the day (universe-wide)'))
    op.add_column('calculated_metrics', sa.Column('universe_down_count', sa.Integer(), nullable=True, comment='# stocks down for the day (universe-wide)'))
    op.add_column('calculated_metrics', sa.Column('mcclellan_oscillator', sa.Numeric(precision=10, scale=4), nullable=True, comment='McClellan Oscillator (advances-declines)'))
    op.add_column('calculated_metrics', sa.Column('mcclellan_summation', sa.Numeric(precision=12, scale=4), nullable=True, comment='McClellan Summation Index (cumulative)'))
    op.add_column('calculated_metrics', sa.Column('rs_ratio', sa.Numeric(precision=10, scale=4), nullable=True, comment='(security close / benchmark close) * 100'))
    op.add_column('calculated_metrics', sa.Column('rs_momentum', sa.Numeric(precision=10, scale=4), nullable=True, comment='1-week ROC of RS-Ratio, smoothed'))
    op.add_column('calculated_metrics', sa.Column('is_green_candle', sa.Integer(), nullable=True, comment='1 if close >= open, else 0'))
    op.add_column('calculated_metrics', sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    op.alter_column('calculated_metrics', 'vcp_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Integer(),
               comment='1-5 based on narrowing range over 3-5 bars',
               existing_comment='Volatility Contraction Pattern score (0-100)',
               existing_nullable=True)
    op.alter_column('calculated_metrics', 'stage',
               existing_type=sa.INTEGER(),
               comment='1=Basing, 2A=Early Uptrend, 2B=At Darvas 100%, 2C=Extended (7x ATR), 3=Topping, 4=Declining',
               existing_comment='Market stage: 1=Accumulation, 2=Markup, 3=Distribution, 4=Decline',
               existing_nullable=True)
    op.drop_index('idx_metrics_rs_rating_desc', table_name='calculated_metrics')
    op.create_index('idx_metrics_date_rs', 'calculated_metrics', ['date', sa.text('rs_percentile DESC')], unique=False)
    op.create_index('idx_metrics_rs_percentile_desc', 'calculated_metrics', [sa.text('rs_percentile DESC')], unique=False)
    op.create_index('idx_metrics_vars_desc', 'calculated_metrics', [sa.text('vars_score DESC')], unique=False)
    op.create_index('idx_metrics_volume_surge', 'calculated_metrics', ['is_volume_surge', 'date'], unique=False)
    op.drop_column('calculated_metrics', 'ma_10')
    op.drop_column('calculated_metrics', 'vol_20d_avg')
    op.drop_column('calculated_metrics', 'atr')
    op.drop_column('calculated_metrics', 'ma_50')
    op.drop_column('calculated_metrics', 'atr_pct')
    op.drop_column('calculated_metrics', 'ma_20')
    op.drop_column('calculated_metrics', 'vars_value')
    op.drop_column('calculated_metrics', 'rs_rating')
    op.drop_column('calculated_metrics', 'ma_200')
    op.drop_column('calculated_metrics', 'vol_vs_avg_pct')
    op.drop_index('idx_fundamental_date', table_name='surveillance_fundamental_flags')
    op.create_index('idx_fundamental_date', 'surveillance_fundamental_flags', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_surveillance_date', table_name='surveillance_list')
    op.create_index('idx_surveillance_date', 'surveillance_list', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_price_movement_date', table_name='surveillance_price_movement')
    op.create_index('idx_price_movement_date', 'surveillance_price_movement', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    op.drop_index('idx_price_variation_date', table_name='surveillance_price_variation')
    op.create_index('idx_price_variation_date', 'surveillance_price_variation', ['date'], unique=False, postgresql_ops={'date': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_price_variation_date', table_name='surveillance_price_variation', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_price_variation_date', 'surveillance_price_variation', [sa.text('date DESC')], unique=False)
    op.drop_index('idx_price_movement_date', table_name='surveillance_price_movement', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_price_movement_date', 'surveillance_price_movement', [sa.text('date DESC')], unique=False)
    op.drop_index('idx_surveillance_date', table_name='surveillance_list', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_surveillance_date', 'surveillance_list', [sa.text('date DESC')], unique=False)
    op.drop_index('idx_fundamental_date', table_name='surveillance_fundamental_flags', postgresql_ops={'date': 'DESC'})
    op.create_index('idx_fundamental_date', 'surveillance_fundamental_flags', [sa.text('date DESC')], unique=False)
    op.add_column('calculated_metrics', sa.Column('vol_vs_avg_pct', sa.NUMERIC(precision=8, scale=2), autoincrement=False, nullable=True, comment='Current volume vs 20-day average (%)'))
    op.add_column('calculated_metrics', sa.Column('ma_200', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='200-day simple moving average'))
    op.add_column('calculated_metrics', sa.Column('rs_rating', sa.NUMERIC(precision=5, scale=2), autoincrement=False, nullable=True, comment='Relative Strength rating (0-100)'))
    op.add_column('calculated_metrics', sa.Column('vars_value', sa.NUMERIC(precision=10, scale=4), autoincrement=False, nullable=True, comment='Value-Adjusted Relative Strength'))
    op.add_column('calculated_metrics', sa.Column('ma_20', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='20-day simple moving average'))
    op.add_column('calculated_metrics', sa.Column('atr_pct', sa.NUMERIC(precision=8, scale=4), autoincrement=False, nullable=True, comment='ATR as percentage of close price'))
    op.add_column('calculated_metrics', sa.Column('ma_50', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='50-day simple moving average'))
    op.add_column('calculated_metrics', sa.Column('atr', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='Average True Range (absolute)'))
    op.add_column('calculated_metrics', sa.Column('vol_20d_avg', sa.BIGINT(), autoincrement=False, nullable=True, comment='20-day average volume'))
    op.add_column('calculated_metrics', sa.Column('ma_10', sa.NUMERIC(precision=15, scale=2), autoincrement=False, nullable=True, comment='10-day simple moving average'))
    op.drop_index('idx_metrics_volume_surge', table_name='calculated_metrics')
    op.drop_index('idx_metrics_vars_desc', table_name='calculated_metrics')
    op.drop_index('idx_metrics_rs_percentile_desc', table_name='calculated_metrics')
    op.drop_index('idx_metrics_date_rs', table_name='calculated_metrics')
    op.create_index('idx_metrics_rs_rating_desc', 'calculated_metrics', [sa.text('rs_rating DESC')], unique=False)
    op.alter_column('calculated_metrics', 'stage',
               existing_type=sa.INTEGER(),
               comment='Market stage: 1=Accumulation, 2=Markup, 3=Distribution, 4=Decline',
               existing_comment='1=Basing, 2A=Early Uptrend, 2B=At Darvas 100%, 2C=Extended (7x ATR), 3=Topping, 4=Declining',
               existing_nullable=True)
    op.alter_column('calculated_metrics', 'vcp_score',
               existing_type=sa.Integer(),
               type_=sa.NUMERIC(precision=5, scale=2),
               comment='Volatility Contraction Pattern score (0-100)',
               existing_comment='1-5 based on narrowing range over 3-5 bars',
               existing_nullable=True)
    op.drop_column('calculated_metrics', 'updated_at')
    op.drop_column('calculated_metrics', 'is_green_candle')
    op.drop_column('calculated_metrics', 'rs_momentum')
    op.drop_column('calculated_metrics', 'rs_ratio')
    op.drop_column('calculated_metrics', 'mcclellan_summation')
    op.drop_column('calculated_metrics', 'mcclellan_oscillator')
    op.drop_column('calculated_metrics', 'universe_down_count')
    op.drop_column('calculated_metrics', 'universe_up_count')
    op.drop_column('calculated_metrics', 'stage_detail')
    op.drop_column('calculated_metrics', 'is_m30_reclaim')
    op.drop_column('calculated_metrics', 'orh_proxy')
    op.drop_column('calculated_metrics', 'is_new_20d_low')
    op.drop_column('calculated_metrics', 'is_new_20d_high')
    op.drop_column('calculated_metrics', 'darvas_position_percent')
    op.drop_column('calculated_metrics', 'darvas_20d_low')
    op.drop_column('calculated_metrics', 'darvas_20d_high')
    op.drop_column('calculated_metrics', 'is_lod_tight')
    op.drop_column('calculated_metrics', 'lod_atr_percent')
    op.drop_column('calculated_metrics', 'atr_extension_from_sma50')
    op.drop_column('calculated_metrics', 'is_ma_stacked')
    op.drop_column('calculated_metrics', 'distance_from_sma200_percent')
    op.drop_column('calculated_metrics', 'distance_from_sma50_percent')
    op.drop_column('calculated_metrics', 'distance_from_ema10_percent')
    op.drop_column('calculated_metrics', 'sma_200')
    op.drop_column('calculated_metrics', 'sma_100')
    op.drop_column('calculated_metrics', 'sma_50')
    op.drop_column('calculated_metrics', 'sma_20')
    op.drop_column('calculated_metrics', 'ema_10')
    op.drop_column('calculated_metrics', 'is_volume_surge')
    op.drop_column('calculated_metrics', 'rvol')
    op.drop_column('calculated_metrics', 'volume_50d_avg')
    op.drop_column('calculated_metrics', 'today_range_percent')
    op.drop_column('calculated_metrics', 'adr_percent')
    op.drop_column('calculated_metrics', 'atr_percent')
    op.drop_column('calculated_metrics', 'atr_14')
    op.drop_column('calculated_metrics', 'varw_score')
    op.drop_column('calculated_metrics', 'vars_score')
    op.drop_column('calculated_metrics', 'rs_percentile')
    op.drop_column('calculated_metrics', 'change_6m_percent')
    op.drop_column('calculated_metrics', 'change_3m_percent')
    op.drop_column('calculated_metrics', 'change_1m_percent')
    op.drop_column('calculated_metrics', 'change_1w_percent')
    op.drop_column('calculated_metrics', 'change_1d_value')
    op.drop_column('calculated_metrics', 'change_1d_percent')
    # ### end Alembic commands ###
