"""Create all database tables (11 tables)

Revision ID: f77b45d8af68
Revises: 
Create Date: 2025-11-23 05:15:33.075674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f77b45d8af68'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('block_deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Deal execution date'),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Security symbol'),
    sa.Column('security_name', sa.String(length=255), nullable=True, comment='Security name from CSV'),
    sa.Column('client_name', sa.String(length=255), nullable=False, comment='Name of client/institution'),
    sa.Column('deal_type', sa.String(length=10), nullable=True, comment='BUY or SELL'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='Number of shares traded'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Trade execution price per share'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_block_deals_client', 'block_deals', ['client_name'], unique=False)
    op.create_index('idx_block_deals_date_symbol', 'block_deals', ['date', 'symbol'], unique=False)
    op.create_index(op.f('ix_block_deals_date'), 'block_deals', ['date'], unique=False)
    op.create_index(op.f('ix_block_deals_symbol'), 'block_deals', ['symbol'], unique=False)
    op.create_table('bulk_deals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Deal execution date'),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Security symbol'),
    sa.Column('security_name', sa.String(length=255), nullable=True, comment='Security name from CSV'),
    sa.Column('client_name', sa.String(length=255), nullable=False, comment='Name of client/institution'),
    sa.Column('deal_type', sa.String(length=10), nullable=True, comment='BUY or SELL'),
    sa.Column('quantity', sa.BigInteger(), nullable=False, comment='Number of shares traded'),
    sa.Column('price', sa.Numeric(precision=15, scale=2), nullable=False, comment='Trade execution price per share'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_bulk_deals_client', 'bulk_deals', ['client_name'], unique=False)
    op.create_index('idx_bulk_deals_date_symbol', 'bulk_deals', ['date', 'symbol'], unique=False)
    op.create_index(op.f('ix_bulk_deals_date'), 'bulk_deals', ['date'], unique=False)
    op.create_index(op.f('ix_bulk_deals_symbol'), 'bulk_deals', ['symbol'], unique=False)
    op.create_table('indices',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('index_name', sa.String(length=100), nullable=False, comment="Full index name (e.g., 'Nifty 50')"),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment="Upstox symbol (e.g., 'Nifty 50' or instrument key)"),
    sa.Column('exchange', sa.String(length=20), nullable=True, comment='Exchange identifier for API calls'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether index is tracked'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('index_name')
    )
    op.create_index(op.f('ix_indices_symbol'), 'indices', ['symbol'], unique=True)
    op.create_table('ingestion_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False, comment="Data source identifier (e.g., 'nse_securities', 'upstox_ohlcv', 'nse_market_cap')"),
    sa.Column('status', sa.String(length=20), nullable=False, comment="Execution status: 'success', 'failure', or 'partial'"),
    sa.Column('records_fetched', sa.Integer(), nullable=True, comment='Number of records fetched from source'),
    sa.Column('records_inserted', sa.Integer(), nullable=True, comment='Number of new records inserted'),
    sa.Column('records_updated', sa.Integer(), nullable=True, comment='Number of existing records updated'),
    sa.Column('records_failed', sa.Integer(), nullable=True, comment='Number of records that failed validation/insertion'),
    sa.Column('errors', sa.JSON(), nullable=True, comment='JSON array of error details for debugging'),
    sa.Column('execution_time_ms', sa.Integer(), nullable=True, comment='Execution time in milliseconds'),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Execution timestamp for this ingestion run'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_logs_source'), 'ingestion_logs', ['source'], unique=False)
    op.create_index(op.f('ix_ingestion_logs_timestamp'), 'ingestion_logs', ['timestamp'], unique=False)
    op.create_table('market_holidays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False, comment='Holiday date in YYYY-MM-DD format'),
    sa.Column('holiday_name', sa.String(length=255), nullable=False, comment='Holiday description from Upstox API'),
    sa.Column('holiday_type', sa.String(length=50), nullable=True, comment='Type: TRADING_HOLIDAY, SETTLEMENT_HOLIDAY, or SPECIAL_TIMING'),
    sa.Column('closed_exchanges', sa.JSON(), nullable=True, comment="JSON array of closed exchanges (e.g., ['NSE', 'NFO', 'BSE'])"),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_holidays_holiday_date'), 'market_holidays', ['holiday_date'], unique=True)
    op.create_table('ohlcv_daily',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Security symbol or index name'),
    sa.Column('date', sa.Date(), nullable=False, comment='Trading date'),
    sa.Column('open', sa.Numeric(precision=15, scale=2), nullable=False, comment='Opening price'),
    sa.Column('high', sa.Numeric(precision=15, scale=2), nullable=False, comment='Highest price of the day'),
    sa.Column('low', sa.Numeric(precision=15, scale=2), nullable=False, comment='Lowest price of the day'),
    sa.Column('close', sa.Numeric(precision=15, scale=2), nullable=False, comment='Closing price'),
    sa.Column('volume', sa.BigInteger(), nullable=True, comment='Trading volume (NULL for indices)'),
    sa.Column('vwap', sa.Numeric(precision=15, scale=2), nullable=True, comment='Volume-Weighted Average Price'),
    sa.Column('prev_close', sa.Numeric(precision=15, scale=2), nullable=True, comment='Previous day closing price'),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True, comment='Percentage change from prev_close'),
    sa.Column('upper_circuit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Upper circuit limit'),
    sa.Column('lower_circuit', sa.Numeric(precision=15, scale=2), nullable=True, comment='Lower circuit limit'),
    sa.Column('week_52_high', sa.Numeric(precision=15, scale=2), nullable=True, comment='52-week high price'),
    sa.Column('week_52_low', sa.Numeric(precision=15, scale=2), nullable=True, comment='52-week low price'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('close >= low AND close <= high', name='ck_close_in_range'),
    sa.CheckConstraint('high >= low', name='ck_high_gte_low'),
    sa.CheckConstraint('open >= low AND open <= high', name='ck_open_in_range'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_ohlcv_symbol_date')
    )
    op.create_index('idx_ohlcv_date_desc', 'ohlcv_daily', [sa.text('date DESC')], unique=False)
    op.create_index('idx_ohlcv_symbol_date_desc', 'ohlcv_daily', ['symbol', sa.text('date DESC')], unique=False)
    op.create_index(op.f('ix_ohlcv_daily_date'), 'ohlcv_daily', ['date'], unique=False)
    op.create_index(op.f('ix_ohlcv_daily_symbol'), 'ohlcv_daily', ['symbol'], unique=False)
    op.create_table('securities',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment="NSE trading symbol (e.g., 'RELIANCE', 'TCS')"),
    sa.Column('isin', sa.String(length=12), nullable=False, comment="12-character ISIN code starting with 'IN'"),
    sa.Column('security_name', sa.String(length=255), nullable=False, comment='Full company/ETF name'),
    sa.Column('series', sa.String(length=10), nullable=True, comment="Trading series (e.g., 'EQ', 'BE')"),
    sa.Column('listing_date', sa.Date(), nullable=True, comment='Date of listing on NSE'),
    sa.Column('paid_up_value', sa.Numeric(precision=15, scale=2), nullable=True, comment='Paid-up value in rupees'),
    sa.Column('market_lot', sa.Integer(), nullable=True, comment='Minimum trading quantity'),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True, comment='Face value per share'),
    sa.Column('security_type', sa.Enum('EQUITY', 'ETF', name='securitytype'), nullable=False, comment='EQUITY or ETF'),
    sa.Column('is_active', sa.Boolean(), nullable=True, comment='Whether security is currently traded'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_securities_is_active'), 'securities', ['is_active'], unique=False)
    op.create_index(op.f('ix_securities_isin'), 'securities', ['isin'], unique=True)
    op.create_index(op.f('ix_securities_symbol'), 'securities', ['symbol'], unique=True)
    op.create_table('surveillance_measures',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('date', sa.Date(), nullable=False, comment='Date surveillance measure was reported'),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Security symbol under surveillance'),
    sa.Column('security_name', sa.String(length=255), nullable=True, comment='Security name from CSV'),
    sa.Column('measure_type', sa.String(length=100), nullable=True, comment="Type of measure (e.g., 'ASM Stage 1', 'GSM', 'Short Term ASM')"),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='Reason for surveillance (if provided in CSV)'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_surveillance_date_symbol', 'surveillance_measures', ['date', 'symbol'], unique=False)
    op.create_index('idx_surveillance_measure_type', 'surveillance_measures', ['measure_type'], unique=False)
    op.create_index(op.f('ix_surveillance_measures_date'), 'surveillance_measures', ['date'], unique=False)
    op.create_index(op.f('ix_surveillance_measures_symbol'), 'surveillance_measures', ['symbol'], unique=False)
    op.create_table('calculated_metrics',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('rs_rating', sa.Numeric(precision=5, scale=2), nullable=True, comment='Relative Strength rating (0-100)'),
    sa.Column('vars_value', sa.Numeric(precision=10, scale=4), nullable=True, comment='Value-Adjusted Relative Strength'),
    sa.Column('atr', sa.Numeric(precision=15, scale=2), nullable=True, comment='Average True Range (absolute)'),
    sa.Column('atr_pct', sa.Numeric(precision=8, scale=4), nullable=True, comment='ATR as percentage of close price'),
    sa.Column('stage', sa.Integer(), nullable=True, comment='Market stage: 1=Accumulation, 2=Markup, 3=Distribution, 4=Decline'),
    sa.Column('vcp_score', sa.Numeric(precision=5, scale=2), nullable=True, comment='Volatility Contraction Pattern score (0-100)'),
    sa.Column('vol_20d_avg', sa.BigInteger(), nullable=True, comment='20-day average volume'),
    sa.Column('vol_vs_avg_pct', sa.Numeric(precision=8, scale=2), nullable=True, comment='Current volume vs 20-day average (%)'),
    sa.Column('ma_10', sa.Numeric(precision=15, scale=2), nullable=True, comment='10-day simple moving average'),
    sa.Column('ma_20', sa.Numeric(precision=15, scale=2), nullable=True, comment='20-day simple moving average'),
    sa.Column('ma_50', sa.Numeric(precision=15, scale=2), nullable=True, comment='50-day simple moving average'),
    sa.Column('ma_200', sa.Numeric(precision=15, scale=2), nullable=True, comment='200-day simple moving average'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['securities.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_metrics_symbol_date')
    )
    op.create_index('idx_metrics_rs_rating_desc', 'calculated_metrics', [sa.text('rs_rating DESC')], unique=False)
    op.create_index('idx_metrics_stage', 'calculated_metrics', ['stage'], unique=False)
    op.create_index('idx_metrics_symbol_date_desc', 'calculated_metrics', ['symbol', sa.text('date DESC')], unique=False)
    op.create_index(op.f('ix_calculated_metrics_date'), 'calculated_metrics', ['date'], unique=False)
    op.create_index(op.f('ix_calculated_metrics_symbol'), 'calculated_metrics', ['symbol'], unique=False)
    op.create_table('industry_classification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Security symbol (foreign key to securities table)'),
    sa.Column('macro', sa.String(length=100), nullable=True, comment='Macro-level classification (broadest)'),
    sa.Column('sector', sa.String(length=100), nullable=True, comment='Sector classification'),
    sa.Column('industry', sa.String(length=100), nullable=True, comment='Industry classification'),
    sa.Column('basic_industry', sa.String(length=100), nullable=True, comment='Basic industry (most specific)'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='Last update timestamp - classification can change'),
    sa.ForeignKeyConstraint(['symbol'], ['securities.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_industry_classification_industry'), 'industry_classification', ['industry'], unique=False)
    op.create_index(op.f('ix_industry_classification_sector'), 'industry_classification', ['sector'], unique=False)
    op.create_index(op.f('ix_industry_classification_symbol'), 'industry_classification', ['symbol'], unique=True)
    op.create_table('market_cap_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.String(length=50), nullable=False, comment='Security symbol (foreign key to securities table)'),
    sa.Column('date', sa.Date(), nullable=False, comment='Market cap calculation date'),
    sa.Column('series', sa.String(length=10), nullable=True, comment='Trading series'),
    sa.Column('security_name', sa.String(length=255), nullable=True, comment='Security name from CSV'),
    sa.Column('category', sa.String(length=50), nullable=True, comment='Market cap category (if provided)'),
    sa.Column('last_trade_date', sa.Date(), nullable=True, comment='Last trading date for the security'),
    sa.Column('face_value', sa.Numeric(precision=10, scale=2), nullable=True, comment='Face value per share'),
    sa.Column('issue_size', sa.BigInteger(), nullable=True, comment='Total issued shares'),
    sa.Column('close_price', sa.Numeric(precision=15, scale=2), nullable=True, comment='Closing price on this date'),
    sa.Column('market_cap', sa.Numeric(precision=20, scale=2), nullable=False, comment='Market capitalization in ₹ crore'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol'], ['securities.symbol'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol', 'date', name='uq_marketcap_symbol_date')
    )
    op.create_index('idx_marketcap_date_mcap_desc', 'market_cap_history', ['date', sa.text('market_cap DESC')], unique=False)
    op.create_index('idx_marketcap_symbol_date_desc', 'market_cap_history', ['symbol', sa.text('date DESC')], unique=False)
    op.create_index(op.f('ix_market_cap_history_date'), 'market_cap_history', ['date'], unique=False)
    op.create_index(op.f('ix_market_cap_history_market_cap'), 'market_cap_history', ['market_cap'], unique=False)
    op.create_index(op.f('ix_market_cap_history_symbol'), 'market_cap_history', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_cap_history_symbol'), table_name='market_cap_history')
    op.drop_index(op.f('ix_market_cap_history_market_cap'), table_name='market_cap_history')
    op.drop_index(op.f('ix_market_cap_history_date'), table_name='market_cap_history')
    op.drop_index('idx_marketcap_symbol_date_desc', table_name='market_cap_history')
    op.drop_index('idx_marketcap_date_mcap_desc', table_name='market_cap_history')
    op.drop_table('market_cap_history')
    op.drop_index(op.f('ix_industry_classification_symbol'), table_name='industry_classification')
    op.drop_index(op.f('ix_industry_classification_sector'), table_name='industry_classification')
    op.drop_index(op.f('ix_industry_classification_industry'), table_name='industry_classification')
    op.drop_table('industry_classification')
    op.drop_index(op.f('ix_calculated_metrics_symbol'), table_name='calculated_metrics')
    op.drop_index(op.f('ix_calculated_metrics_date'), table_name='calculated_metrics')
    op.drop_index('idx_metrics_symbol_date_desc', table_name='calculated_metrics')
    op.drop_index('idx_metrics_stage', table_name='calculated_metrics')
    op.drop_index('idx_metrics_rs_rating_desc', table_name='calculated_metrics')
    op.drop_table('calculated_metrics')
    op.drop_index(op.f('ix_surveillance_measures_symbol'), table_name='surveillance_measures')
    op.drop_index(op.f('ix_surveillance_measures_date'), table_name='surveillance_measures')
    op.drop_index('idx_surveillance_measure_type', table_name='surveillance_measures')
    op.drop_index('idx_surveillance_date_symbol', table_name='surveillance_measures')
    op.drop_table('surveillance_measures')
    op.drop_index(op.f('ix_securities_symbol'), table_name='securities')
    op.drop_index(op.f('ix_securities_isin'), table_name='securities')
    op.drop_index(op.f('ix_securities_is_active'), table_name='securities')
    op.drop_table('securities')
    op.drop_index(op.f('ix_ohlcv_daily_symbol'), table_name='ohlcv_daily')
    op.drop_index(op.f('ix_ohlcv_daily_date'), table_name='ohlcv_daily')
    op.drop_index('idx_ohlcv_symbol_date_desc', table_name='ohlcv_daily')
    op.drop_index('idx_ohlcv_date_desc', table_name='ohlcv_daily')
    op.drop_table('ohlcv_daily')
    op.drop_index(op.f('ix_market_holidays_holiday_date'), table_name='market_holidays')
    op.drop_table('market_holidays')
    op.drop_index(op.f('ix_ingestion_logs_timestamp'), table_name='ingestion_logs')
    op.drop_index(op.f('ix_ingestion_logs_source'), table_name='ingestion_logs')
    op.drop_table('ingestion_logs')
    op.drop_index(op.f('ix_indices_symbol'), table_name='indices')
    op.drop_table('indices')
    op.drop_index(op.f('ix_bulk_deals_symbol'), table_name='bulk_deals')
    op.drop_index(op.f('ix_bulk_deals_date'), table_name='bulk_deals')
    op.drop_index('idx_bulk_deals_date_symbol', table_name='bulk_deals')
    op.drop_index('idx_bulk_deals_client', table_name='bulk_deals')
    op.drop_table('bulk_deals')
    op.drop_index(op.f('ix_block_deals_symbol'), table_name='block_deals')
    op.drop_index(op.f('ix_block_deals_date'), table_name='block_deals')
    op.drop_index('idx_block_deals_date_symbol', table_name='block_deals')
    op.drop_index('idx_block_deals_client', table_name='block_deals')
    op.drop_table('block_deals')
    # ### end Alembic commands ###
